#! /bin/sh
MAVEN_OPTS=-agentlib:${PWD}/agent_nodejs_linux64
LD_LIBRARY_PATH=${LD_LIBRARY_PATH};${PWD}
PATH=${PATH};${PWD}
IASTAGENT_LOGGING_STDERR_LEVEL=info
IASTAGENT_LOGGING_STDERR_ENABLED=true 
mvn --batch-mode test